on:
  push:
    paths:
      - 'gov-*.md'
  workflow_dispatch:
jobs:
  generate_docs:
    name: Generate artifacts
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: pandoc texlive-latex-base texlive-xetex texlive-latex-extra texlive-extra-utils texlive-fonts-recommended
        version: 1.0

    - name: re-run config See https://github.com/awalsh128/cache-apt-pkgs-action/issues/57
      run: sudo updmap-sys --nohash; sudo mktexlsr /var/lib/texmf; sudo fmtutil-sys --all

    - name: generate html
      run: for SRC in `ls gov-*.md`; do export BASE=`basename ${SRC} .md`; pandoc --css pandoc.css -s --toc-depth 2 --toc --pdf-engine xelatex -f markdown ${SRC} --metadata pagetitle="Gamle Oslo Venstre bydelsprogram 2023-2027" | perl -wple 's/eps/svg/' > ${BASE}.html; done

    - name: generate PDF
      run: for SRC in `ls gov-*.md`; do export BASE=`basename ${SRC} .md`; pandoc --pdf-engine xelatex --toc -f markdown ${SRC} -o ${BASE}.pdf; done

    - name: push html and pdf
      uses: test-room-7/action-update-file@v1
      with:
        file-path: |
          *.pdf
          *.html
        commit-msg: Auto-update HTML/PDF
        github-token: ${{ secrets.GITHUB_TOKEN }}
