on:
  workflow_dispatch:
jobs:
  generate_docs:
    name: Generate artifacts
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v1

    - name: install dependencies
      run: sudo apt install pandoc
  
    - name: generate html
      run: export SRC=`ls gov-*.md`; export BASE=`basename ${SRC} .md`; pandoc --css pandoc.css -s --toc-depth 2 --toc --pdf-engine xelatex -f markdown ${SRC} --metadata pagetitle="Gamle Oslo Venstre bydelsprogram 2023-2027" | perl -wple 's/eps/svg/' > ${BASE}.html

    - name: generate PDF
      run: export SRC=`ls gov-*.md`; export BASE=`basename ${SRC} .md`; pandoc --pdf-engine xelatex --toc -f markdown ${SRC} -o ${BASE}.pdf
