on:
  workflow_dispatch:
jobs:
  generate_docs:
    name: Generate artifacts
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v1

    - name: install dependencies
      run: apt install pandoc
  
    - name: generate html
      run: pandoc --css pandoc.css -s --toc-depth 2 --toc --pdf-engine xelatex -f markdown gov-bydelsprogram-2023-2027.md --metadata pagetitle="Gamle Oslo Venstre bydelsprogram 2023-2027" | perl -wple 's/eps/svg/' > gov-bydelsprogram-2023-2027.html

    - name: generate PDF
      run: pandoc --pdf-engine xelatex --toc -f markdown gov-bydelsprogram-2023-2027.md -o gov-bydelsprogram-2023-2027.pdf
